### ISSUE TITLE
MetaMaskService.ConnectMetaMask() does not connect

### ISSUE THREAD

**Issue by moccajoghurt** [michielpost/MetaMask.Blazor#3]
After upgrading to .NET 6 and installing the newest Version of MetaMask my connection to MetaMask no longer works.
Here is a Blazor button that used to work and doesn't anymore:

MetamaskConnectButton.razor
```
<MudIconButton OnClick="@ConnectMetaMask">
    @if (IsConnected) {
        <img src="images/metamask-fox.svg" style="margin: auto; width: 30px;" alt=""/>
    }
    else {
        <img src="images/metamask-fox_gray.svg" style="margin: auto; width: 30px;" alt=""/>
    }
</MudIconButton>
```

MetamaskConnectButton.razor.cs
```
using System;
using System.Threading.Tasks;
using MetaMask.Blazor;
using Microsoft.AspNetCore.Components;

namespace GenMintWebsite.Client.Shared; 

public partial class MetamaskConnectButton : ComponentBase, IDisposable {
    public bool IsConnected { get; set; }
    [Inject] public MetaMaskService MetaMaskService { get; set; } = default!;

    protected override async Task OnInitializedAsync() {
        if (!await MetaMaskService.HasMetaMask()) return;
        MetaMaskService.AccountChangedEvent += MetaMaskService_AccountChangedEvent;
        await MetaMaskService.ListenToEvents();
        IsConnected = await MetaMaskService.IsSiteConnected();
    }

    public async Task ConnectMetaMask() {
        if (!await MetaMaskService.HasMetaMask()) return;
        if (IsConnected) return;
        await MetaMaskService.ConnectMetaMask();
    }

    private async Task MetaMaskService_AccountChangedEvent(string arg) {
        IsConnected = await MetaMaskService.IsSiteConnected();
        StateHasChanged();
    }

    public void Dispose() {
        MetaMaskService.AccountChangedEvent -= MetaMaskService_AccountChangedEvent;
    }
}
```

It seems like the interaction between the MetaMask browser plugin and MetaMask.Blazor no longer works.
I am running on the latest Chrome Version 96.0.4664.45 (64-Bit)

**Comment by michielpost** [comment]
Thanks, it was hard to reproduce but it looks like sometimes MetaMask returnes `undefined` for selectedAddress instead of null. Not sure if this is a change causes by MetaMask or .net 6. But I think I fixed it.

Can you try again with version 1.3.1 from NuGet and let me know if that works?

**Comment by moccajoghurt** [comment]
@michielpost Thanks for the quick reply and commit.
The error still exists and I have the exact same error when I use the sample app you provided in this repository.

When I press "Initialize connection with MetaMask" on the [startscreen](https://i.imgur.com/mypNZIj.png), nothing happens and the button press gets stuck in `await module.InvokeVoidAsync("checkMetaMask");` forever.
However, when I reload the page once after starting the app, the login always works.
And then it also works in the sample I provided.

I will keep digging.

**Comment by moccajoghurt** [comment]
Still inside the scope of your sample app:
If I don't reload the page once before pressing the connect button, the javascript call to:
```
var result = await ethereum.request({
        method: 'eth_requestAccounts',
    });
```
never returns and Metamask does not pop up either. (.NET6, Visual Studio 2022, latest Chrome, latest MetaMask).

**Comment by michielpost** [comment]
Can you try this sample?
https://2g0462afspq58aenh81tbbdnuvq21kmji82n0qqgn4he9vcrsnu2ql0.siasky.net/

I'm unable to reproduce it there. It opens the first time I press the button. A second time it throws an error that it's still waiting from a response from the first request, but I think that's just how MetaMask works.

**Comment by moccajoghurt** [comment]
@michielpost this sample works right away.

**Comment by michielpost** [comment]
Ok, great to hear. This sample is based on the latest NuGet release. So that should work. Maybe do a hard refresh to clear the cache of any old js files.

**Comment by moccajoghurt** [comment]
@michielpost It must have something to do with cached chrome / VS 2022 files.
When I do a fresh clone of your repository and start the sample, it works as expected.
Once I start the sample a second time, I have the weird error that requires a refresh.

So this isn't a problem with the code but the environment. Sorry for wasting our time.

**Comment by michielpost** [comment]
No problem, at least 1 bug is fixed and I also noticed some weird caching from Chrome. Not sure what was going on there.
